name: CFML TestBox Test Runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 build:

  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v2
   - uses: Ortus-University/ou-testbox-mb-action@master